name: Deploy V1.0

# WORKFLOW SETUP : 
# 1 : Generate token (write:packages, delete:packages)
# 2 : Add secret ['secrets.SERVER_HOST','secrets.SERVER_USER','secrets.SERVER_SSH_KEY','secrets.SERVER_PORT',"ghrcToken","ghrcUser"]


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Fix uppercase issues with URLs
      - name: UPPER to lower
        run: |
          echo "ACTOR_LOWER=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Track updates
      - name: Set up Git for checking changes
        run: git fetch --prune --unshallow

      # Check changes on BOT
      - name: Checking update on BOT
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^bot.py'; then
            echo "BOT_CHANGED=true" >> $GITHUB_ENV
          else
            echo "BOT_CHANGED=false" >> $GITHUB_ENV
          fi

      # Stop if no changes were made
      - name: Stop if no changes were made to the bot.py
        run: |
          if [[ "$BOT_CHANGED" == "false" ]]; then
            echo "Aucun changement dans le bot.py, arrÃªt du workflow."
            exit 0
          fi

      - name: Login
        run: echo "${{ secrets.ghrcToken }}" | docker login ghcr.io -u ${{ secrets.ghrcUser }} --password-stdin


      # BUILD BOT
      - name: Build BOT
        if: env.BOT_CHANGED == 'true'
        run: |
          docker build -f Dockerfile -t ghcr.io/${{ env.REPO_LOWER }}/bot:latest .
          docker push ghcr.io/${{ env.REPO_LOWER }}/bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest


    # Rebuild without downtime, only if changes were made + remove unused images
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT}}
          script: |
            cd /opt/bot-element/
            pwd
            echo "${{ secrets.ghrcToken }}" | docker login ghcr.io -u ${{ secrets.ghrcUser }} --password-stdin
            git pull origin main
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d --remove-orphans
            docker image prune -f